
< unique.cmd
errlogInit(20000)

< envPaths

#epicsThreadSleep(20)
dbLoadDatabase("$(AD{{ cookiecutter.driver_name }})/iocs/{{ cookiecutter.driver_name[0].lower() + cookiecutter.driver_name[1:] }}IOC/dbd/{{ cookiecutter.driver_name[0].lower() + cookiecutter.driver_name[1:] }}App.dbd")
{{ cookiecutter.driver_name[0].lower() + cookiecutter.driver_name[1:] }}App_registerRecordDeviceDriver(pdbbase) 

#/*
# * Constructor for AD{{ cookiecutter.driver_name }} driver. Most params are passed to the parent ADDriver constructor. 
# * Connects to the camera, then gets device information, and is ready to aquire images.
# *
# * NOTE THAT THIS IS AUTOGENERATED BY THE TEMPLATE, IT IS POSSIBLE THAT YOUR DETECTOR DOES NOT USE 
# * SERIAL NUMBER TO CONNECT, AND THIS MUST BE CHANGED
# * 
# * @params: portName -> port for NDArray recieved from camera
# * @params: serial -> serial number of device to connect to
# * @params: maxBuffers -> max buffer size for NDArrays
# * @params: maxMemory -> maximum memory allocated for driver
# * @params: priority -> what thread priority this driver will execute with
# * @params: stackSize -> size of the driver on the stack
# */


#
# AD{{ cookiecutter.driver_name }}Config(const char* portName, const char* serial, int maxBuffers, size_t maxMemory, int priority, int stackSize)
# epicsThreadSleep(2)

# If searching for device by product ID put "" or empty string for serial number
AD{{ cookiecutter.driver_name }}Config("$(PORT)", $(CAM-CONNECT), 0, 0, 0, 0)
epicsThreadSleep(2)

asynSetTraceIOMask($(PORT), 0, 2)
#asynSetTraceMask($(PORT),0,0xff)

dbLoadRecords("$(ADCORE)/db/ADBase.template", "P=$(PREFIX),R=cam1:,PORT=$(PORT),ADDR=0,TIMEOUT=1")
dbLoadRecords("$(AD{{ cookiecutter.driver_name }})/db/AD{{ cookiecutter.driver_name }}.template","P=$(PREFIX),R=cam1:,PORT=$(PORT),ADDR=0,TIMEOUT=1")

#
# Create a standard arrays plugin, set it to get data from Driver.
#int NDStdArraysConfigure(const char *portName, int queueSize, int blockingCallbacks, const char *NDArrayPort, int NDArrayAddr, int maxBuffers, size_t maxMemory,
#                          int priority, int stackSize, int maxThreads)
NDStdArraysConfigure("Image1", 3, 0, "$(PORT)", 0)
#dbLoadRecords("$(ADCORE)/db/NDPluginBase.template","P=$(PREFIX),R=image1:,PORT=Image1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),NDARRAY_ADDR=0")
#dbLoadRecords("$(ADCORE)/db/NDStdArrays.template", "P=$(PREFIX),R=image1:,PORT=Image1,ADDR=0,TIMEOUT=1,TYPE=Int16,SIZE=16,FTVL=SHORT,NELEMENTS=802896")
dbLoadRecords("$(ADCORE)/db/NDStdArrays.template", "P=$(PREFIX),R=image1:,PORT=Image1,ADDR=0,NDARRAY_PORT=$(PORT),TIMEOUT=1,TYPE=Int16,FTVL=SHORT,NELEMENTS=20000000")

#
# Load all other plugins using commonPlugins.cmd
< $(ADCORE)/iocBoot/commonPlugins.cmd
#

set_requestfile_path("$(AD{{ cookiecutter.driver_name }})/{{ cookiecutter.driver_name[0].lower() + cookiecutter.driver_name[1:] }}App/Db")

#asynSetTraceMask($(PORT),0,0x09)
#asynSetTraceMask($(PORT),0,0x11)
iocInit()

# save things every thirty seconds
create_monitor_set("auto_settings.req", 30, "P=$(PREFIX)")
